<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="planar_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="length" value="1" /> <!-- Link length -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find planar_bot_description)/urdf/planar_bot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find planar_bot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${0.75*width}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${1.5*width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${0.75*width}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${1.5*width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${0.75*width}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>
  
  <link name="link1">
    <collision>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (length*length + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (length*length + width*width)}"/>
    </inertial>
  </link>
  
  <link name="link2">
    <collision>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <inertial>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (length*length + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (length*length + width*width)}"/>
    </inertial>
  </link>
  
  <link name="link3">
    <collision>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (length*length + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (length*length + width*width)}"/>
    </inertial>
  </link>
  
  <link name="link4">
    <collision>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${width}"/>
      </geometry>
      <material name="yellow"/>
    </visual>

    <inertial>
      <origin xyz="${length/2 - axel_offset} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + width*width)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (length*length + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (length*length + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${2*width}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="80" velocity="8.0" lower="-0.3" upper="3.45" />
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${length - axel_offset*2} 0 ${-width}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="80" velocity="8.0" lower="-3.0" upper="3.0" />
  </joint>
  
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${length - axel_offset*2} 0 ${width}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="80" velocity="8.0" lower="-3.0" upper="3.0" />
  </joint>
  
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="${length - axel_offset*2} 0 ${-width}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="80" velocity="8.0" lower="-3.0" upper="3.0" />
  </joint>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
