planar_bot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # RMRC Controller
  rmrc_controller:
    type: "planar_bot_control/RMRCController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    task_space_error_feedback_gain: 5.0
    
  # ASC Controller
  asc_controller:
    type: "planar_bot_control/ASCController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    task_space_error_feedback_gain: 5.0
